development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: penguin_development
  pool: 5
  username: penguin
  password: buzhidao

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: penguin_test
  pool: 5
  username: penguin
  password: buzhidao

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: penguin_production
  pool: 5
  username: penguin
  password: buzhidao